### ISSUE TITLE
Font-family matters

### ISSUE THREAD

**Issue by trebird** [trebird/horizontal-nav#1]
Hi again!

I'm concerned with my h1 value for font-family. It seems to be wrong either way I enter it (w/ or w/o quotes, w/ or w/o sans-serif, cursive etc).

Thank you, @thomasjbradley

**Comment by trebird** [comment]
Hi once more,

I'm really having trouble figuring out/understanding how to get the last nav element to move when the page width is 400px

Thank you!

@thomasjbradley

**Comment by thomasjbradley** [comment]
`Bevan` is a `serif` font, so what you’re looking for is this: `font-family: Bevan, serif;`

**Comment by trebird** [comment]
Thank you!
